/**
 * PaStats Metrics - Unit Alert Handler
 * Runs in the live_game_unit_alert scene (child panel of live_game)
 *
 * Responsibilities:
 *  1. Intercept army_defeated events (commander kills) and forward them
 *     to the parent panel (gamedata.js) via Panel message.
 *  2. Filter the popup alerts generated by our mod's watchlist registration
 *     so only the "important" ones reach the UI, like the original PA Stats
 *     mod used to do.
 *
 * Popup filtering strategy (inspired by ColaColin's alertsManager.js):
 *  - For CREATED / DESTROYED / TARGET_DESTROYED / ALLIED_DEATH:
 *      only let through units whose categories match a whitelist
 *      (Factory / Commander / Recon / Important), and exclude Walls.
 *  - For SIGHT:
 *      * first ever sighting of an enemy army: reclassify to FIRST_CONTACT
 *        when the first unit seen is NOT an important category (tanks, bots,
 *        mex, etc). PA shows a single "Enemy located!" banner per army
 *        instead of spamming a sight popup for every mobile unit.
 *      * subsequent sightings: keep SIGHT for important units only,
 *        suppress for regular mobile units, exclude Walls.
 *      * if the unit type mapping isn't loaded yet, be pessimistic and
 *        reclassify new-army sights to FIRST_CONTACT so we never spam
 *        during the ~1-3s startup window.
 *  - For IDLE / ARRIVAL: always suppress (too spammy).
 *  - For DAMAGED / FIRST_CONTACT / PING / PROJECTILE / everything else:
 *      leave untouched so PA's native handling stays intact.
 *
 * Safety fallbacks:
 *  - Unit type mapping loads asynchronously (~1-3s at game start). While
 *    the map isn't ready, every popup of a filtered type is allowed through
 *    (except SIGHT on new armies which is reclassified to FIRST_CONTACT).
 *  - If a unit spec isn't in the map (modded unit), the popup is allowed
 *    through — same behavior as the original PA Stats mod.
 *
 * Our data collector in the parent live_game scene still receives every
 * event via its own handlers.watch_list override; this file only trims
 * what the PA popup UI displays.
 *
 * ES5 Compatible for Planetary Annihilation (Coherent GT webview).
 *
 * @author MarechalGryzzly
 * @version 4.0
 */

var paStatsUnitAlertPrefix = "[PAStats:Kill]";

// ==================== WATCH TYPE CONSTANTS ====================
// Numeric IDs sent by the PA engine in payload.list[i].watch_type.
var _PAS_WT_CREATED = 0;
var _PAS_WT_DESTROYED = 2;
var _PAS_WT_SIGHT = 4;
var _PAS_WT_FIRST_CONTACT = 6;
var _PAS_WT_TARGET_DESTROYED = 7;
var _PAS_WT_ALLIED_DEATH = 8;
var _PAS_WT_IDLE = 9;
var _PAS_WT_ARRIVAL = 10;

// ==================== FILTER CONFIG ====================
// For each watch_type we handle, which unit categories to keep / exclude.
// Categories are the UNITTYPE_* tags declared in the unit JSON files
// (with the UNITTYPE_ prefix stripped).
var _paStatsFilterSettings = {
  selectedTypes: {},
  excludedTypes: {}
};

// CREATED - show factory/recon/important finishing construction (enemy & ally)
_paStatsFilterSettings.selectedTypes[_PAS_WT_CREATED] =
  ['Factory', 'Recon', 'Important'];

// DESTROYED - show when a factory, commander, recon or important unit dies
_paStatsFilterSettings.selectedTypes[_PAS_WT_DESTROYED] =
  ['Factory', 'Commander', 'Recon', 'Important'];
_paStatsFilterSettings.excludedTypes[_PAS_WT_DESTROYED] = ['Wall'];

// SIGHT - show only important enemies once they are visible (Factory / Commander
// / Recon / Important). Regular mobile units on already-seen armies are filtered
// out here. First-time sightings are reclassified to FIRST_CONTACT beforehand
// in _paStatsReclassifySights().
_paStatsFilterSettings.selectedTypes[_PAS_WT_SIGHT] =
  ['Factory', 'Commander', 'Recon', 'Important'];
_paStatsFilterSettings.excludedTypes[_PAS_WT_SIGHT] = ['Wall'];

// TARGET_DESTROYED - our watched unit killed an enemy; only notify for meaningful kills
_paStatsFilterSettings.selectedTypes[_PAS_WT_TARGET_DESTROYED] =
  ['Factory', 'Commander', 'Recon', 'Important'];
_paStatsFilterSettings.excludedTypes[_PAS_WT_TARGET_DESTROYED] = ['Wall'];

// ALLIED_DEATH - important for team games (allied commander / factory lost)
_paStatsFilterSettings.selectedTypes[_PAS_WT_ALLIED_DEATH] =
  ['Factory', 'Commander', 'Recon', 'Important'];
_paStatsFilterSettings.excludedTypes[_PAS_WT_ALLIED_DEATH] = ['Wall'];

// Watch types we always suppress - PA doesn't show these by default, and our
// recording-only registration would otherwise surface them as popup spam.
var _paStatsAlwaysSuppress = {};
_paStatsAlwaysSuppress[_PAS_WT_IDLE] = true;
_paStatsAlwaysSuppress[_PAS_WT_ARRIVAL] = true;

// ==================== STATE ====================
// Army IDs we've already observed a sight event for. Used to reclassify the
// very first sighting of a new army to FIRST_CONTACT when the first unit
// seen is not an important category.
var _paStatsSeenArmyIds = {};

// ==================== UNIT TYPE MAPPING ====================
// spec_id (JSON path) -> array of unit type tags (e.g. ['Mobile', 'Factory']).
// Loaded asynchronously; stays undefined until the $.getJSON chain finishes.
var _paStatsUnitTypeMap = undefined;

if (typeof paStatsUnitInfoParser !== "undefined") {
  paStatsUnitInfoParser.loadUnitTypeMapping(function (mapping) {
    _paStatsUnitTypeMap = mapping;
    console.log(
      paStatsUnitAlertPrefix +
      " Unit type mapping loaded: " +
      Object.keys(mapping).length + " units"
    );
  });
} else {
  console.log(
    paStatsUnitAlertPrefix +
    " WARNING: paStatsUnitInfoParser not available, popup filter will pass everything through."
  );
}

// ==================== HELPERS ====================

function _paStatsContains(arr, value) {
  if (!arr) return false;
  for (var i = 0; i < arr.length; i++) {
    if (arr[i] === value) return true;
  }
  return false;
}

/**
 * First-pass reclassification: turn first-ever sightings of "non-important"
 * enemy units into FIRST_CONTACT so PA shows a single "Enemy located!" banner
 * per army instead of spamming a sight popup for every mobile unit.
 *
 * Behavior for a SIGHT alert on an unseen army:
 *   - If the unit type mapping isn't loaded yet -> reclassify to FIRST_CONTACT
 *     (pessimistic - avoids spam during the ~1-3s startup window).
 *   - If the unit is NOT in the SIGHT selectedTypes (tanks, bots, mex, etc.)
 *     -> reclassify to FIRST_CONTACT.
 *   - If the unit IS in the SIGHT selectedTypes (Factory/Commander/Recon
 *     /Important) -> leave as SIGHT so the main filter keeps the popup.
 *
 * Once an army has been observed, we mark it in _paStatsSeenArmyIds and stop
 * reclassifying; subsequent SIGHT events flow through the normal category
 * filter.
 */
function _paStatsReclassifySights(list) {
  var sightSelected = _paStatsFilterSettings.selectedTypes[_PAS_WT_SIGHT];

  for (var i = 0; i < list.length; i++) {
    var alert = list[i];
    var wt = alert.watch_type;
    if (wt === undefined) wt = alert.alert_type;
    if (wt !== _PAS_WT_SIGHT) continue;

    if (alert.army_id === undefined) continue;
    if (_paStatsSeenArmyIds[alert.army_id]) continue;

    // First time we see this army. Decide if the first unit visible is
    // important enough to keep SIGHT, otherwise reclassify to FIRST_CONTACT.
    _paStatsSeenArmyIds[alert.army_id] = true;

    // Pessimistic fallback: mapping not loaded yet -> assume not important.
    if (_paStatsUnitTypeMap === undefined) {
      alert.watch_type = _PAS_WT_FIRST_CONTACT;
      continue;
    }

    var unitTypes = _paStatsUnitTypeMap[alert.spec_id];
    if (unitTypes === undefined) {
      // Unknown unit (modded): keep as SIGHT so the main filter's
      // unknown-unit fallback lets it through.
      continue;
    }

    var isImportant = false;
    for (var n = 0; n < sightSelected.length; n++) {
      if (_paStatsContains(unitTypes, sightSelected[n])) {
        isImportant = true;
        break;
      }
    }

    if (!isImportant) {
      alert.watch_type = _PAS_WT_FIRST_CONTACT;
    }
  }
}

/**
 * Decide whether a single alert entry should be shown by PA's popup UI.
 * Returns true to keep the popup, false to suppress it.
 */
function _paStatsShouldKeepAlert(notice) {
  var wt = notice.watch_type;
  if (wt === undefined) wt = notice.alert_type;

  // 1) Always-suppress types (idle, arrival)
  if (_paStatsAlwaysSuppress[wt]) return false;

  // 2) Types we don't filter (damaged, first_contact, ping, projectile, etc.)
  //    Leave popup decision entirely to PA's native logic.
  if (_paStatsFilterSettings.selectedTypes[wt] === undefined) {
    return true;
  }

  // 3) Filtered types - need the unit type mapping.
  //    Fallback: while mapping isn't loaded yet, allow everything.
  if (_paStatsUnitTypeMap === undefined) {
    return true;
  }

  var unitTypes = _paStatsUnitTypeMap[notice.spec_id];

  // 4) Unknown unit spec (e.g. modded unit not in unit_list.json):
  //    keep the popup - the original PA Stats mod does the same.
  if (unitTypes === undefined) {
    return true;
  }

  var excluded = _paStatsFilterSettings.excludedTypes[wt] || [];
  var selected = _paStatsFilterSettings.selectedTypes[wt] || [];

  // 5) Any excluded tag wins over selected - e.g. Walls never produce popups
  for (var i = 0; i < excluded.length; i++) {
    if (_paStatsContains(unitTypes, excluded[i])) return false;
  }

  // 6) Must match at least one selected tag to show
  for (var j = 0; j < selected.length; j++) {
    if (_paStatsContains(unitTypes, selected[j])) return true;
  }

  return false;
}

// ==================== WATCH_LIST HOOK ====================

var _paStatsOrigWatchList = handlers.watch_list;

handlers.watch_list = function (payload) {
  if (payload && payload.list) {
    // Pass 1: reclassify first-ever sightings of non-important enemies
    // from SIGHT to FIRST_CONTACT so PA shows a single "Enemy located!"
    // banner per army, not a sight popup per mobile unit.
    _paStatsReclassifySights(payload.list);

    // Pass 2: drop entries we don't want popups for
    var filtered = [];
    for (var i = 0; i < payload.list.length; i++) {
      if (_paStatsShouldKeepAlert(payload.list[i])) {
        filtered.push(payload.list[i]);
      }
    }
    payload.list = filtered;
  }

  // Call PA's native popup handler with the trimmed list (if anything remains)
  if (_paStatsOrigWatchList && payload && payload.list && payload.list.length > 0) {
    _paStatsOrigWatchList(payload);
  }
};

// ==================== ARMY DEFEATED (COMMANDER KILLS) ====================

/**
 * Handle army defeated events (commander kills).
 * Lets PA render its native "XYZ has been defeated" banner, then forwards
 * the payload to the data collector in the parent scene.
 */
handlers.army_defeated = function (payload) {
  try {
    model.processArmyDefeated(payload);
  } catch (e) {
    console.log(
      paStatsUnitAlertPrefix + " ERROR in processArmyDefeated: " + e.message
    );
  }

  api.Panel.message(api.Panel.parentId, "comKillData", payload);
};
